# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-master
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: study-computer
      POSTGRES_USER: study2019
      POSTGRES_PASSWORD: study2019
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

volumes:
  postgres-data:
